# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'
  #vmImage:'win2016'
variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/TransportACE.Droid.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    clean: true
    msbuildVersion: 'latest'
    jdkOption: 'JDKVersion'

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'apacheta-release-key.keystore'
    apksignerKeystorePassword: '$(keystore-password)'
    apksignerKeystoreAlias: '$(key-alias)'
    apksignerKeyPassword: '$(key-password)'
    apksignerArguments: --out $(outputDirectory)/TransportACE.apk
    zipalign: true


- task: CopyFiles@2
  inputs:
      SourceFolder: '$(outputDirectory)'
      Contents: '**/*.apk'
      TargetFolder: '$(build.artifactStagingDirectory)'
      OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'apks'
      publishLocation: 'Container'     


  
  
